import Head from 'next/head'
import { PostCard, PostWidget, Categories } from '../components'
import {getPosts} from '../services'



// const posts = [
//   {
//     title: 'Why does your growth mindset never work out the way you plan?', excerpt: 'Look, To be honest, understand that growth mindset doesn\'t define your intelligence or your personality or anything else about you.Instead, as What did i learn from that experience? How can I use it as a basis for growth?'
//   },
//   {
//     title: 'Folk remedies for improving your life using a growth mindset.', excerpt: '90% of the living beings on this planet want to be loved. Similarly like every other person we also feel the same although sometimes we try to show that love and affection to our loved ones. Why not just part ways being the same person? What I mean is let’s just segregate the love we give to  others and the love we do to ourselves . Unfortunately this balance may not stay the same for many of us.'
//   },
// ]

export default function Home({posts}) {
  return (
    <div className="container mx-auto px-10 mb-8">
      <Head>
        <title>WonderWall Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='grid grid-cols-1 lg:grid-cols-12 gap-12'>
        <div className='lg:col-span-8 col-span-1'>
          {posts.map((post, index) =>
            <PostCard key={index} post={post.node}  />)}
        </div>
        <div className='lg:col-span-4 col-span-1'>
          <div className='lg:sticky relative top-8'>
            <PostWidget />
            <Categories />
          </div>
        </div>
      </div>
    </div>
  );
}


export async function getStaticProps() {
  const posts = (await getPosts()) || [];

  return{
    props: { posts },
  }
}